-- Generated by the Quickshell "Display" settings page (profile: "Kiri-kanan").
-- Do not edit by hand: it is overwritten on the next apply.
-- Profiles live in ~/.config/hypr/displays/profiles.json.

-- Layar laptop
hl.monitor({ output = "eDP-2", mode = "2560x1440@165", position = "0x0", scale = "1.333333" })
-- SKYDATA F24G41F
hl.monitor({ output = "desc:SKYDATA S.P.A. F24G41F 0x01010101", mode = "1920x1080@240", position = "1925x2", scale = "1" })
