-- Generated by the Quickshell "Display" settings page (profile: "Kiri-kanan").
-- Do not edit by hand: it is overwritten on the next apply.

hl.workspace_rule({ workspace = "1", monitor = "desc:SKYDATA S.P.A. F24G41F 0x01010101", default = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:SKYDATA S.P.A. F24G41F 0x01010101" })
hl.workspace_rule({ workspace = "3", monitor = "desc:SKYDATA S.P.A. F24G41F 0x01010101" })
hl.workspace_rule({ workspace = "4", monitor = "eDP-2" })
hl.workspace_rule({ workspace = "5", monitor = "eDP-2" })
