# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/
# monitor=eDP-1,2560x1440@165,0x0,1

gesture = 3, swipe, unset, move
gesture = 4, horizontal, unset, workspace
# gesture = 4, pinch, unset, float
gesture = 4, up,   unset, dispatcher, global, quickshell:overviewToggle
gesture = 4, down, unset, dispatcher, global, quickshell:overviewClose

misc {
    on_focus_under_fullscreen = 1
}

# workspace: 3-jari kiri/kanan
gesture = 3, horizontal, workspace

# overview: 3-jari up & down sama-sama toggle
gesture = 3, up,   dispatcher, global, quickshell:overviewWorkspacesToggle
gesture = 3, down, dispatcher, global, quickshell:overviewWorkspacesToggle

input {
  touchpad {
    clickfinger_behavior = false
    tap-to-click = true
    tap_button_map = lrm
  }
}
