# See https://wiki.hyprland.org/Configuring/Binds/
#!
##! User
bind = Ctrl+Super, Slash, exec, xdg-open ~/.config/illogical-impulse/config.json # Edit shell config
bind = Ctrl+Super+Alt, Slash, exec, xdg-open ~/.config/hypr/custom/keybinds.conf # Edit extra keybinds

# Add stuff here
# Use #! to add an extra column on the cheatsheet
# Use ##! to add a section in that column
# Add a comment after a bind to add a description, like above

##! Ganang's Workspace & Focus

# --- Super+Tab / Super+Shift+Tab: pindah workspace relatif ---
unbind = Super, Tab                                           
bind = Super, Tab,       exec, ~/.config/hypr/custom/scripts/ws12-mode.sh next     #Next WS →
bind = Super+Shift, Tab, exec, ~/.config/hypr/custom/scripts/ws-cycle.sh prev     #Prev WS ←

# --- Alt+Tab: pindah fokus antar window di workspace aktif ---
bind   = Alt, Tab,       cyclenext           # Next Wdw → 
bind   = Alt+Shift, Tab, cyclenext, prev     # Prev Wdw ← 

# Toggle mode: Super + ` (backtick)
unbind = Super, grave
bind   = Super, grave, exec, ~/.config/hypr/custom/scripts/ws12-mode.sh toggle   #Mode memasak

unbind = Super, Super_L
unbind = Super, Super_R

# --- Bind baru: Super+D untuk Overview ---
unbind = Super, D
bind = Super+Ctrl, F, fullscreen, 1 # Maximize
bind = Super, D, global, quickshell:overviewWorkspacesToggle    # Toggle overview

# New bind because screenshot with qml got bugs from the qml scale
unbind = Super+Shift, S

# Pakai hyprshot sebagai region screenshot utama
# bind = Super+Shift, S, exec, hyprshot --freeze --clipboard-only -m region --silent #SS Using Hyprshot No Save
bind = Super+Shift, S, exec, hyprshot -m region --freeze --output-folder /home/notsuperganang/Pictures/screenshots --silent  #SS using Hyprshot Saved
# bind = Super+Shift, S, exec, hyprshot -m region --freeze --output-folder /home/notsuperganang/Documents/tugas-akhir/pages --silent  #SS using Hyprshot Saved Custom Path
